version: '2'
services:
  frontend:
    image: chat-frontend
    build: frontend
    environment:
      - BACKEND_URL=
    restart: always
      
  backend:
    image: chat-backend
    build: .
    restart: always
      
  proxy:
    image: chat-proxy
    build: nginx
    ports:
      - 64152:80
    restart: always
